DeepConv1D:
  in_channels: 1
  conv_channels: [32, 64, 128, 128, 256, 512] 
  kernels:   [9, 9, 9, 9, 9, 7, 7]
  strides:   [3, 3, 3, 3, 3, 3, 7]
  paddings:  [3, 3, 3, 3, 3, 2, 0]

DeepConv1D_latent:
  in_channels: 4
  conv_channels: [32, 64, 128, 256]
  kernels:   [7, 5, 3, 3]
  strides:   [2, 2, 2, 2]
  paddings:  [3, 2, 1, 0]
