VAE_params:
  z_channels: 4
  down_channels : [128, 256, 512, 512]
  mid_channels : [512, 512]
  down_sample : [True, True, True]
  attn_down : [False, False, True]   # attention at deepest downsample too
  norm_channels: 32
  num_heads: 8
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2
  conv_kernel_size: [4,4,4]
  conv_kernel_strides: [2,2,2]
  transpose_kernel_size: [4,4,4]
  transpose_kernel_strides: [2,2,2]
  output_padding: [0, 1, 1]
  beta: 1e-7